stages:
  data_ingestion :
    cmd :
      - python src/Chess/pipeline/stage_01_DataIngestion.py
    deps :
      - src/Chess/pipeline/stage_01_DataIngestion.py
      - config/config.yaml
    outs :
      - artifacts/Data/raw_games.pgn
  data_validation:
    cmd: python src/Chess/pipeline/stage_02_DataValidation.py
    deps:
      - src/Chess/pipeline/stage_02_DataValidation.py
      - artifacts/Data/raw_games.pgn
      - config/config.yaml

  data_transformation:
      cmd: python src/Chess/pipeline/stage_03_DataTransformation.py
      deps:
        - src/Chess/pipeline/stage_03_DataTransformation.py
        - artifacts/Data/raw_games.pgn
        - config/config.yaml
      outs:
        - artifacts/data_transformation/X.npy
        - artifacts/data_transformation/Y.npy

  prepare_base_Model:
    cmd:
      - python src/Chess/pipelien/stage_04_PrepareBaseModel
    deps:
      - src/Chess/pipelien/stage_04_PrepareBaseModel.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/prepare_base_model/base_model_updated.h5
      - artifacts/prepare_base_model/model.h5
    params:
      - IMAGE_SIZE
      - CLASSES
      - LEARNING_RATE

