IMAGE_SIZE: [8, 8, 12]
CLASSES: 4096
LEARNING_RATE: 0.0003
EPOCHS: 50
BATCH_SIZE: 32
VALIDATION_SPLIT : 0.2
SHUFFLE : TRUE

D_MODEL: 128
NUM_HEADS: 4
FF_DIM: 512
NUM_LAYERS: 4
IN_CHANNELS: 12
NUM_MOVES: 4096
