artifacts_root : artifacts

data_ingestion :
  root_dir: artifacts/data_ingestion
  source_file: artifacts/lichess_db_standard_rated_2013-06.pgn
  local_data_file: artifacts/data_ingestion/raw_games.pgn
  source_URL : https://database.lichess.org/standard/lichess_db_standard_rated_2013-06.pgn.zst
  unzip_dir : artifacts/Data

data_validation :
  root_dir : artifacts/data_validation
  source_file : artifacts/Data/raw_games.pgn
  status_file : artifacts/data_validation/status.json

data_transformation :
  status_file: artifacts/data_validation/status.json
  root_dir : artifacts/data_transformation
  data_path : artifacts/Data/raw_games.pgn
  transformed_data_dir: artifacts/data_transformation/processed

prepare_base_Model :
  root_dir : artifacts/prepare_base_model
  model_path : artifacts/prepare_base_model/model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

prepare_train_model:
  root_dir: artifacts/prepare_callbacks
  trained_model_path: artifacts/prepare_callbacks/trained_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  transformed_x_path: artifacts/data_transformation/X.npy
  transformed_y_path: artifacts/data_transformation/Y.npy

evaluate_base_model :
  root_dir : artifacts/evaluate
  trained_model_path: artifacts/prepare_callbacks/trained_model.h5
  evaluated_model_path : artifacts/evaluate/evaluated_base_model/evaluated_base_model.h5

  source_URL : https://database.lichess.org/standard/lichess_db_standard_rated_2016-02.pgn.zst
  unzip_dir : artifacts/evaluate/Data  #UNZIP DIR
  local_data_file  : artifacts/evaluate/Data_Ingestion #Download DIR

  source_file : artifacts/evaluate/Data
  status_file  : artifacts/evaluate/data_validation/status.json

  data_path : artifacts/evaluate/Data
  transformed_data_dir: artifacts/data_transformation/processed

  evaluate_scores : artifacts/evaluate/scores


